application:
    name: auth-service-dev
    port: 8081
    path: "/security"
    env: "development"
    log:
        file: "auth-service-dev.log"
        level: info
        json: false

database:
    url: "mongodb://root:rootpassword@localhost:27017/?retryWrites=true&w=majority&authSource=admin"
    database: "auth-service"

authentication:
    algorithm: "HS256"
    secret: "67uzoULtouBbSpwjVvzVQ5D1APKTc3i9"
    accessExpirationMinutes: 15
    refreshExpirationDays: 7
    refreshTokenName: refreshTokenDev
    issuer: auth-service-dev
    audience:
        - commander
        - auth-service-dev
    salt: 10
